version: '3.9'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ../proxy:/etc/nginx/templates
      - ../certs:/etc/nginx/ssl
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://0.0.0.0:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://0.0.0.0:3000}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8081:8081"
    command: /bin/sh -c "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
