version: '3.9'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ../proxy:/etc/nginx/templates     
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://192.168.0.55:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://192.168.0.55:3000}
    ports:
      - target: 80
        published: 80
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081

