blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: hello@wonnetwork.org
    about: Request a feature or enhancement
  - name: Ask a question
    url: https://t.me/WonCommunity
    about: Ask questions and discuss topics with other community members
  - name: Join our Facebook
    url: hhttps://www.facebook.com/WonNetworkEcoSystem
    about: The official WonNetwork Facebook community